### ISSUE TITLE
AS number is indicated as optional while it is in fact required with default settings

### ISSUE THREAD

**Issue by ties** [NLnetLabs/routinator-ui#17]
As a user I find this confusing:
<img width="922" alt="Screenshot 2021-07-06 at 15 25 29" src="https://user-images.githubusercontent.com/199058/124607787-74116d00-de6e-11eb-9ef5-0c60b7928457.png">

**Comment by density215** [comment]
I don't seem to be able to find the right UX around this, so it'll probably take some fiddling and taking things back and forth before something workable for everybody comes out.

The core of the problem is that we have two inputs here, and sometimes they are both required, and sometimes they aren't. The default now is that only a prefix is required on landing on the empty page. If you start typing in the ASN box, that default will be switched off and the UI expects to get a (valid) ASN from the user.

 This will only get worse when we allow searching on an ASN, btw.

**Comment by ties** [comment]
I did not realise that was happening and it explains why I could not reproduce it.

Maybe they are separate forms (also visually)? Switching a default that is not visually near the field you are touching is not clear to me... So perhaps the three (in the future) cases should be three separate forms.

**Comment by density215** [comment]
Validating with an origin ASN found in BGP is now the default, so the ASN field is optional. 

You may still encounter this behavior if a query parameter in the URL like this: `validate_bgp=false` was set.
